// <auto-generated />
using System;
using CleanArchitecture.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace CleanArchitecture.Persistence.Migrations
{
    [DbContext(typeof(AtDbContext))]
    partial class AtDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("CleanArchitecture.Domain.Entities.User.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:IdentitySequenceOptions", "'12', '1', '', '', 'False', '1'")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("Deleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Email")
                        .HasColumnType("character varying(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Name")
                        .HasColumnType("character varying(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Password")
                        .HasColumnType("character varying(256)")
                        .HasMaxLength(256);

                    b.Property<string>("Username")
                        .HasColumnType("character varying(50)")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.HasIndex("Username", "Email", "Active", "Deleted")
                        .IsUnique();

                    b.ToTable("Persons");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Active = true,
                            Created = new DateTime(2021, 9, 11, 21, 10, 54, 471, DateTimeKind.Local).AddTicks(6122),
                            Deleted = false,
                            Email = "Sincere@april.biz",
                            Name = "Leanne Graham",
                            Password = "534547",
                            Username = "Bret"
                        },
                        new
                        {
                            Id = 2,
                            Active = true,
                            Created = new DateTime(2021, 9, 11, 21, 10, 54, 474, DateTimeKind.Local).AddTicks(5421),
                            Deleted = false,
                            Email = "Shanna@melissa.tv",
                            Name = "Ervin Howell",
                            Password = "521333",
                            Username = "Antonette"
                        },
                        new
                        {
                            Id = 3,
                            Active = true,
                            Created = new DateTime(2021, 9, 11, 21, 10, 54, 474, DateTimeKind.Local).AddTicks(5730),
                            Deleted = false,
                            Email = "Nathan@yesenia.net",
                            Name = "Clementine Bauch",
                            Password = "433774",
                            Username = "Samantha"
                        },
                        new
                        {
                            Id = 4,
                            Active = true,
                            Created = new DateTime(2021, 9, 11, 21, 10, 54, 474, DateTimeKind.Local).AddTicks(5781),
                            Deleted = false,
                            Email = "Julianne.OConner@kory.org",
                            Name = "Patricia Lebsack",
                            Password = "577615",
                            Username = "Karianne"
                        },
                        new
                        {
                            Id = 5,
                            Active = true,
                            Created = new DateTime(2021, 9, 11, 21, 10, 54, 474, DateTimeKind.Local).AddTicks(5825),
                            Deleted = false,
                            Email = "Lucio_Hettinger@annie.ca",
                            Name = "Chelsey Dietrich",
                            Password = "671265",
                            Username = "Kamren"
                        },
                        new
                        {
                            Id = 6,
                            Active = true,
                            Created = new DateTime(2021, 9, 11, 21, 10, 54, 474, DateTimeKind.Local).AddTicks(5878),
                            Deleted = false,
                            Email = "Karley_Dach@jasper.info",
                            Name = "Mrs. Dennis Schulist",
                            Password = "662143",
                            Username = "Leopoldo_Corkery"
                        },
                        new
                        {
                            Id = 7,
                            Active = true,
                            Created = new DateTime(2021, 9, 11, 21, 10, 54, 474, DateTimeKind.Local).AddTicks(5926),
                            Deleted = false,
                            Email = "Telly.Hoeger@billy.biz",
                            Name = "Kurtis Weissnat",
                            Password = "819913",
                            Username = "Elwyn.Skiles"
                        },
                        new
                        {
                            Id = 8,
                            Active = true,
                            Created = new DateTime(2021, 9, 11, 21, 10, 54, 474, DateTimeKind.Local).AddTicks(5969),
                            Deleted = false,
                            Email = "Sherwood@rosamond.me",
                            Name = "Nicholas Runolfsdottir V",
                            Password = "851146",
                            Username = "Maxime_Nienow"
                        },
                        new
                        {
                            Id = 9,
                            Active = true,
                            Created = new DateTime(2021, 9, 11, 21, 10, 54, 474, DateTimeKind.Local).AddTicks(6012),
                            Deleted = false,
                            Email = "Chaim_McDermott@dana.io",
                            Name = "Glenna Reichert",
                            Password = "609162",
                            Username = "Delphine"
                        },
                        new
                        {
                            Id = 10,
                            Active = true,
                            Created = new DateTime(2021, 9, 11, 21, 10, 54, 474, DateTimeKind.Local).AddTicks(6141),
                            Deleted = false,
                            Email = "Rey.Padberg@karina.biz",
                            Name = "Clementina DuBuque",
                            Password = "454915",
                            Username = "Moriah.Stanton"
                        },
                        new
                        {
                            Id = 11,
                            Active = true,
                            Created = new DateTime(2021, 9, 11, 21, 10, 54, 475, DateTimeKind.Local).AddTicks(3737),
                            Deleted = false,
                            Email = "ozgrrr@mail.com",
                            Name = "Default User",
                            Password = "123123123",
                            Username = "ozgrrr"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
